# Site settings
author: ChiEn Leow
title: ChiEn Leow
header-img: img/home-bg.png
email: chienleow1@gmail.com
copyright_name: ChiEn Leow
description: > # this means to ignore newlines until "baseurl:"
  My Career Changing Journey with Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  chienleow

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
